export const ROUTES = {
  login: '/login',
  home: '/',
  users: '/users',
  programs: '/programs',
  programCourses: (programId: string) => `/programs/${programId}/courses`,
  courses: '/courses',
  courseDetail: (courseId: string) => `/courses/${courseId}`,
  courseRuns: '/course-runs',
  courseRunDetail: (runId: string) => `/course-runs/${runId}`,
  lessonDetail: (lessonId: string) => `/lessons/${lessonId}`,
  events: '/events',
  eventDetail: (eventId: string) => `/events/${eventId}`,
  userDetail: (userId: string) => `/users/${userId}`,
  payments: '/payments',
  moderation: '/moderation',
  liveSessions: '/live-sessions',
  notifications: '/notifications',
  auditLogs: '/audit-logs',
  settings: '/settings',
} as const;
