export const ROUTES = {
  login: '/login',
  home: '/',
  users: '/users',
  programs: '/programs',
  programCourses: (programId: string) => `/programs/${programId}/courses`,
  courses: '/courses',
  courseDetail: (courseId: string) => `/courses/${courseId}`,
  courseRuns: '/course-runs',
  courseRunDetail: (runId: string) => `/course-runs/${runId}`,
  syllabusItemDetail: (itemId: string) => `/syllabus-items/${itemId}`,
  events: '/events',
  eventDetail: (eventId: string) => `/events/${eventId}`,
  payments: '/payments',
  moderation: '/moderation',
  auditLogs: '/audit-logs',
} as const;
